[build]
  command = "next build" # Or "npm run build" if you have a custom build script
  publish = ".next" # Or ".next" if you are not using next export

[[plugins]]
  package = "@netlify/plugin-nextjs"